### ISSUE TITLE
Docker-compose compatibility

### ISSUE THREAD

**Issue by BRICKRAID** [flavsdotpy/docker-cronicle-python#1]
Hey, any way to run this in docker-compose?

**Comment by flavsdotpy** [comment]
yeah, should be straightforward by creating a docker compose file with configuration entries similar to what I did in the [makefile goal `run`](https://github.com/flavsdotpy/docker-cronicle-python/blob/main/Makefile#L7), but with an additional paramter with `build: .` as shown in the [docker compose docs](https://docs.docker.com/compose/gettingstarted/#step-2-define-services-in-a-compose-file).
Ill make it and open a PR.
