### ISSUE TITLE
Compatability with cronicle-edge?

### ISSUE THREAD

**Issue by dreaded369** [flavsdotpy/docker-cronicle-python#2]
https://github.com/cronicle-edge/cronicle-edge

Just wondering if this has been tried by someone?

**Comment by flavsdotpy** [comment]
I took some time looking into cronicle-edge docs and I think should be 100% compatible, requires testing tho...

**Comment by dreaded369** [comment]
> I took some time looking into cronicle-edge docs and I think should be 100% compatible, requires testing tho...

I made an attempt.

cronicle-edge has an existing entrypoint, so I avoided the entrypoint.sh. Maybe I could have rewritten it to ultimately end up using tini like cronicle-edge does, but i wasn't sure how to do that.

Instead I: 
 - merged the cronicle-edge and docker-cronicle-python Dockerfiles
 - bypassed the cronicle-edge entrypoint (in docker compose using entrypoint:  ["/bin/bash"]    stdin_open: true   tty: true
docker compose build
 - exec'ed into the container and ran /opt/cronicle/bin/control.sh import /opt/cronicle/import/python.pixl:
'''Cronicle Data Importer v1.0
Importing from file: /opt/cronicle/import/python.pixl

Importing record: global/plugins
Importing record: global/plugins/0
[1718762660.379][ERROR][file] Failed to delete file: global/state: data/global/d3/36/e7/d336e75083d08c96b2e4bba57227c4e8.json: File not found

Import complete. 2 records imported.
Exiting.

cronicle:/opt/cronicle# exit
'''
It exited the docker container on completion.
 - docker compose start
 
 It doesn't appear on the plugins page, nor in the dropdown for scheduling a task.
 
 That's about all I can think of to try - I couldn't find any documention about a pixl file in the cronicle docs.

**Comment by dreaded369** [comment]
could i take the contents of the pixl file and create a JSON file from it to import? Is the second variables just the contents of "params"?

**Comment by flavsdotpy** [comment]
I had to make my own entrypoint just to make sure the import command runs prior to starting the cronicle webserver, otherwise it just restarts the webserver without importing anything! It was the only way I found to make the import work :x but its a plain shell script that just checks if the import never ran, to run it, and then calls the other entrypoint, for cronicle edge it should work by calling tini instead.

The contents of the pixl file is a plain json after the endpoint entry, so if you know how to import the json directly (i read cronicle-edge has some extense import rest API) it would be even easier!

**Comment by dreaded369** [comment]
I got this working - I modified the cronicle-edge Dockerfile slightly, mainly adding py3-pip and adding python-script-plugin.py to ./bin
then once in the cronicle gui I imported the contents of "global/plugins/0 - {"type":"list_page","items":[]" using the Plugin - Import from JSON button.

Ideally it could be all be imported at build time, or the plugin py file also imported with the JSON, but until then the above isn't too bad.

**Comment by flavsdotpy** [comment]
nice man!! great news!! if you setup a fork or something like I did here and want me to help, ill be glad!

**Comment by dreaded369** [comment]
> nice man!! great news!! if you setup a fork or something like I did here and want me to help, ill be glad!

Do yo have much more planned for it? Or would you consider it complete?

If/when it's complete I'd lean towards asking cronicle-edge to integrate it directly.

**Comment by flavsdotpy** [comment]
Only QoL stuff like better error capturing and/or improved metrics. Everything for code execution is already there.

**Comment by dreaded369** [comment]
I was thinking that using the first 5% of progress for the env setup could be good.
